# Application Name
spring.application.name=test-security

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d9d1ruihil2s73b47s20-a.oregon-postgres.render.com:5432/test_security_db

spring.datasource.username=user
spring.datasource.password=qOJeesxI5OaaejZz7ZlPXfRrlebb1Ttm

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool (Optional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000